name: my-github-action-tests

on: push
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
      
      - name: install dependences
        run: make install

      - name: lint
        run: make lint
      
      - name: test
        run: make test
